# info about container and image to be deployed
container:
  repository: 152363175369.dkr.ecr.us-west-2.amazonaws.com
  image: inventory-read
  tag: latest
  port: 9002

# container resources
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 200Mi

consumer:
  enabled: true
  consumers:
    - command: items-updated

# health check configuration
health:
  path: /health
  port: 9002
  initialDelaySeconds: 10
  periodSeconds: 10

# rolling update strategy configuration
strategy:
  maxSurge: 1
  maxUnavailable: 50%

# horizontal scalling configuration
hpa:
  minReplicas: 1
  maxReplicas: 5

# service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 9002
  protocol: TCP

configmap:
  port: 9002
  jwt:
    secret: "QuFsuM4dNSHfsfyjrCQeKAEE4KRj5sQR6Ez4Y6kcCh4XBgzJ43dHSm9mb9Y6kBBfUajgxjAbXRX4FttD"
  sqs:
    region: us-west-2
    path: /.aws/credentials
    profile: personal
  sns:
    region: us-west-2
    path: /.aws/credentials
    profile: personal
  mongodb:
    database: inventory
    connection_string: mongodb+srv://admin:admin@users.ssocs.mongodb.net/?ssl=false
  events:
    items-updated: items-updated
