# info about container and image to be deployed
container:
  repository: 152363175369.dkr.ecr.us-west-2.amazonaws.com
  image: inventory-write
  tag: latest
  port: 9001

# container resources
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 200Mi

# health check configuration
health:
  path: /health
  port: 9001
  initialDelaySeconds: 10
  periodSeconds: 10

# rolling update strategy configuration
strategy:
  maxSurge: 1
  maxUnavailable: 50%

# horizontal scalling configuration
hpa:
  minReplicas: 1
  maxReplicas: 5

# service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 9001
  protocol: TCP

# create new service for grpc

configmap:
  port: 9001
  grpc_port: 9005
  jwt:
    secret: "QuFsuM4dNSHfsfyjrCQeKAEE4KRj5sQR6Ez4Y6kcCh4XBgzJ43dHSm9mb9Y6kBBfUajgxjAbXRX4FttD"
  sqs:
    region: us-west-2
    path: C:/Users/diego/.aws/credentials
    profile: personal
  sns:
    region: us-west-2
    path: C:/Users/diego/.aws/credentials
    profile: personal
  postgres:
    host: tradew-rds.cbkii6q0lg0j.us-west-2.rds.amazonaws.com
    user: myuser
    password: 123123123
    port: 5432
    database: tradew
  events:
    items-updated: items-updated
