# info about container and image to be deployed
container:
  repository: 152363175369.dkr.ecr.us-west-2.amazonaws.com
  image: trades
  tag: latest
  port: 9003

# container resources
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 200Mi

# health check configuration
health:
  path: /health
  port: 9003
  initialDelaySeconds: 10
  periodSeconds: 10

# rolling update strategy configuration
strategy:
  maxSurge: 1
  maxUnavailable: 50%

# horizontal scalling configuration
hpa:
  minReplicas: 1
  maxReplicas: 5

# service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 9003
  protocol: TCP

configmap:
  port: 9003
  jwt:
    secret: "QuFsuM4dNSHfsfyjrCQeKAEE4KRj5sQR6Ez4Y6kcCh4XBgzJ43dHSm9mb9Y6kBBfUajgxjAbXRX4FttD"
  mongodb:
    database: trades
    connection_string: mongodb+srv://admin:admin@users.ssocs.mongodb.net/?ssl=false
  inventory_service:
    url: inventory-write:9005
