# info about container and image to be deployed
container:
  repository: 152363175369.dkr.ecr.us-west-2.amazonaws.com
  image: users
  tag: latest
  port: 9000

# container resources
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 200Mi

# health check configuration
health:
  path: /health
  port: 9000
  initialDelaySeconds: 15
  periodSeconds: 10

# rolling update strategy configuration
strategy:
  maxSurge: 1
  maxUnavailable: 50%

# horizontal scalling configuration
hpa:
  minReplicas: 1
  maxReplicas: 5

# service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 9000
  protocol: TCP

configmap:
  port: 9000
  jwt:
    expiration_in_minutes: 14400
    secret: "QuFsuM4dNSHfsfyjrCQeKAEE4KRj5sQR6Ez4Y6kcCh4XBgzJ43dHSm9mb9Y6kBBfUajgxjAbXRX4FttD"
  mongodb:
    database: users
    connection_string: mongodb+srv://admin:admin@users.ssocs.mongodb.net/?ssl=false
