{{ if .Values.http }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tradew-server
  namespace: {{ .Values.http.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: {{ .Values.http.host }}
    http:
      paths:
{{- range .Values.http.backends }}
      - backend:
          serviceName: {{ .serviceName }}
          servicePort: {{ .servicePort }}
        path: {{ .path }}
{{- end }}
{{ end }}