apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: logs
spec:
  version: 7.13.3
  count: 1
  # http:
  #   service:
  #     spec:
  #       type: LoadBalancer
  elasticsearchRef:
    name: quickstart
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 500Mi
            cpu: 1
          limits:
            memory: 500Mi
            cpu: 1
